create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  options jsonb not null,
  correct_option_index integer not null,
  category text not null,
  explanation text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint questions_options_is_array check (jsonb_typeof(options) = 'array'),
  constraint questions_minimum_options check (jsonb_array_length(options) >= 2),
  constraint questions_correct_option_range check (
    correct_option_index >= 0
    and correct_option_index < jsonb_array_length(options)
  )
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  score integer not null check (score >= 0),
  total_questions integer not null check (total_questions > 0),
  completed_at timestamptz not null default timezone('utc', now())
);

create index if not exists quiz_attempts_user_id_completed_at_idx
  on public.quiz_attempts (user_id, completed_at desc);

alter table public.questions enable row level security;
alter table public.quiz_attempts enable row level security;

revoke all on table public.questions from anon, authenticated;
revoke all on table public.quiz_attempts from anon, authenticated;

grant select (id, question_text, options, category, created_at)
  on public.questions
  to authenticated;

grant insert (user_id, score, total_questions, completed_at), select
  on public.quiz_attempts
  to authenticated;

drop policy if exists "authenticated users can read quiz questions metadata" on public.questions;
drop policy if exists "students can insert their own quiz attempts" on public.quiz_attempts;
drop policy if exists "students can read their own quiz attempts" on public.quiz_attempts;

create policy "authenticated users can read quiz questions metadata"
  on public.questions
  for select
  to authenticated
  using (true);

create policy "students can insert their own quiz attempts"
  on public.quiz_attempts
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "students can read their own quiz attempts"
  on public.quiz_attempts
  for select
  to authenticated
  using (auth.uid() = user_id);

drop function if exists public.get_random_tech_quiz();

create function public.get_random_tech_quiz()
returns table (
  id bigint,
  question_text text,
  options jsonb,
  category text
)
language sql
security definer
set search_path = public
as $$
  select
    q.id,
    q.question_text,
    q.options,
    q.category
  from public.questions q
  order by random()
  limit 50;
$$;

grant execute on function public.get_random_tech_quiz() to authenticated;

drop function if exists public.submit_tech_quiz_attempt(jsonb);

create function public.submit_tech_quiz_attempt(answer_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_total_questions integer;
  v_score integer;
  v_completed_at timestamptz := timezone('utc', now());
  v_missed_questions jsonb;
begin
  if v_user_id is null then
    raise exception 'Authentication required to submit this quiz.';
  end if;

  with submitted_answers as (
    select
      (item ->> 'question_id')::bigint as question_id,
      case
        when item ? 'selected_option_index'
          and item ->> 'selected_option_index' <> ''
        then (item ->> 'selected_option_index')::integer
        else null
      end as selected_option_index
    from jsonb_array_elements(coalesce(answer_payload, '[]'::jsonb)) item
  ),
  matched_questions as (
    select
      q.id,
      q.question_text,
      q.options,
      q.category,
      q.explanation,
      q.correct_option_index,
      s.selected_option_index
    from submitted_answers s
    join public.questions q on q.id = s.question_id
  )
  select
    count(*),
    count(*) filter (where selected_option_index = correct_option_index),
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', id,
          'question_text', question_text,
          'options', options,
          'category', category,
          'explanation', explanation,
          'selected_option_index', selected_option_index,
          'correct_option_index', correct_option_index
        )
      ) filter (where coalesce(selected_option_index, -1) <> correct_option_index),
      '[]'::jsonb
    )
  into v_total_questions, v_score, v_missed_questions
  from matched_questions;

  if coalesce(v_total_questions, 0) = 0 then
    raise exception 'No valid quiz answers were submitted.';
  end if;

  insert into public.quiz_attempts (user_id, score, total_questions, completed_at)
  values (v_user_id, v_score, v_total_questions, v_completed_at);

  return jsonb_build_object(
    'score', v_score,
    'total_questions', v_total_questions,
    'completed_at', v_completed_at,
    'missed_questions', v_missed_questions
  );
end;
$$;

grant execute on function public.submit_tech_quiz_attempt(jsonb) to authenticated;
